# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-09 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='name',
            new_name='title',
        ),
    ]
