# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-09 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190909_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'books', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'publisher', 'verbose_name_plural': 'publisher'},
        ),
    ]
